"""add client first_name last_name

Revision ID: 4e8330d9b3c8
Revises: c03986bec598
Create Date: 2025-12-23 11:17:20.228258

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e8330d9b3c8"
down_revision: Union[str, Sequence[str], None] = "c03986bec598"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("first_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "clients", sa.Column("last_name", sa.String(length=100), nullable=True)
    )

    # ✅ 1) Backfill depuis full_name
    # Règle:
    # - si full_name contient au moins un espace:
    #     last_name = dernier mot
    #     first_name = le reste
    # - sinon:
    #     first_name = full_name
    #     last_name = 'N/A'
    op.execute(
        """
        UPDATE clients
        SET
          first_name = CASE
            WHEN position(' ' in full_name) > 0
              THEN regexp_replace(full_name, '\\s+[^\\s]+\\s*$', '')
            ELSE full_name
          END,
          last_name = CASE
            WHEN position(' ' in full_name) > 0
              THEN regexp_replace(full_name, '^.*\\s+', '')
            ELSE 'N/A'
          END
        WHERE first_name IS NULL OR last_name IS NULL;
        """
    )

    # ✅ 2) Rendre NOT NULL (si tu veux l’imposer)
    op.alter_column(
        "clients", "first_name", existing_type=sa.String(length=100), nullable=False
    )
    op.alter_column(
        "clients", "last_name", existing_type=sa.String(length=100), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "last_name")
    op.drop_column("clients", "first_name")
    # ### end Alembic commands ###
