"""nommage de la contrainte email unique (uq_clients_email)

Revision ID: 73c71b9b972e
Revises: 228e6711b992
Create Date: 2025-12-17 09:44:49.544884

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73c71b9b972e"
down_revision: Union[str, Sequence[str], None] = "228e6711b992"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_clients_email", "clients", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_clients_email", "clients", type_="unique")
    # ### end Alembic commands ###
