"""drop client full_name

Revision ID: a02d68703108
Revises: 4e8330d9b3c8
Create Date: 2025-12-23 11:38:27.995615

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a02d68703108"
down_revision: Union[str, Sequence[str], None] = "4e8330d9b3c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "clients", "last_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "clients", "first_name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
