"""add timestamps to contracts

Revision ID: cfa483117a3d
Revises: 330d2fa9c983
Create Date: 2026-01-08 13:07:23.687921

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfa483117a3d"
down_revision: Union[str, Sequence[str], None] = "330d2fa9c983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contracts", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "updated_at")
    # ### end Alembic commands ###
