"""Ajout FK sales_contact_id dans table clients

Revision ID: d084517a25c7
Revises: 3e15da7afb7e
Create Date: 2025-12-16 14:28:18.922433

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d084517a25c7"
down_revision: Union[str, Sequence[str], None] = "3e15da7afb7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_clients_sales_contact_id_employees",
        "clients",
        "employees",
        ["sales_contact_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_clients_sales_contact_id_employees", "clients", type_="foreignkey"
    )
    # ### end Alembic commands ###
